### ISSUE TITLE
Thanks for this icon pack. How to do this for other colour themes?

### ISSUE THREAD

**Issue by Vibhav201** [xelser/gruvbox-papirus-folders#1]
Can you tell me how exactly did you modify the catppuccin papirus-folders port to make this one?
Basically, how did you colour so many icons into the gruvbox-material palette? 
I want to do the same for different custom colour themes, for example, Dracula. It would be really cool if I could port many themes and then provide them in a single repo. Thanks in advance.

**Comment by xelser** [comment]
Its quite simple actually, I have a bash script for you to start on [here](https://gist.github.com/xelser/597a1bc97809cb26416f0f221e49c58d).
I'm currently making a gtk theme for [this](https://github.com/sainnhe/edge) and eventually make its own papirus folder theme. Which is why I saved the script for future use. Goodluck.

Here's how i did it:
1. clone the catppuccin papirus folder
2. go to folder like `22x22/places`, run the script
3. repeat to other folders.
4. done.

Let me know if you got it to work because its been a while since i've used this script.

**Comment by Vibhav201** [comment]
Thanks for this buddy. I am going to try my best with my almost non-existent bash scripting knowledge. 
You are doing amazing work there by porting the Edge theme by @sainnhe to GTK. Good Luck. As a Plasma user, it would be great if you could also create a set of KDE Colour Schemes for it. You can start with the [Catppuccin KDE Colour](https://github.com/catppuccin/kde/blob/main/Resources/Base.colors) Scheme files as a template. 
I plan on making a Gruvbox-Material port to KDE soon, but I doubt that I'll do a good enough job lol.

**Comment by Vibhav201** [comment]
Hey, I found a similar script which might or might not be better, I don't know for sure. But, it does the same thing and changes the icon colours for the 78 'places' icons.

https://github.com/Adapta-Projects/Papirus-Folder-Icon-Creator

**Comment by Vibhav201** [comment]
Hey, I ran the script you provided, but I am getting the following error 2 times for each colour.
`sed: can't read *red*.tmp: No such file or directory` 
I couldn't resolve it, can you help?

**Comment by xelser** [comment]
It runs just fine on my end. The error is basically saying that it failed to create a file from an svg. Perhaps you did it on the wrong directory (?) 

You have to go where the svgs are.

**Comment by xelser** [comment]
One possibility is you dont have a rename command. IDK about other distros but debian (that is my current distro) has that [package](https://packages.debian.org/bookworm/rename).

**Comment by Vibhav201** [comment]
Thanks for the info because you are correct (well, sort of). After some searching I found that my distro's (Tumbleweed) `rename` command is different than Debian's `rename`.  And, it's actually the `file-rename` command in openSUSE that works like Debian's `rename`. So, I was able to run your script as well. It is actually amazing. 
Your script is a bit difficult to run than [this](https://github.com/Adapta-Projects/Papirus-Folder-Icon-Creator) one but the advantage is that I can create multiple colour icons at the same time. In that one, I would have to run it separately for different colours (red, blue, ...). Thanks again. Now, I can use any one of them depending on the no. of colour sets.

**Comment by Vibhav201** [comment]
I just found out a small bug in your script, one of the icons is named incorrectly because of changing `cat` to some other theme name.
`folder-cat-mocha-red-applications.svg` -> `folder-gruv-mat-hard-dark-aqua-appligruv-mations.svg`

**Comment by xelser** [comment]
I'm glad that you got it to work! :clap:

> Also, I wanted to ask which version of this icon theme looks better to you?

Since you asked I was actually planning to update this one to remove the "light" variant because it looks super dimmed when you have compositor effects that dims the window when its not focused. So my opinion is always stick to lighter colors, only use a dark variant of it if there are words on top of it (bg and fg).

The right one looks better but dim the white a bit more if you want to use a monochrome range(?) since there are no other colors present (red, blue, etc).

> Your script is a bit difficult to run than [this](https://github.com/Adapta-Projects/Papirus-Folder-Icon-Creator) one

I actually didn't know that this existed, i just basically googled my way into creating this script.

**Comment by xelser** [comment]
> I just found out a small bug in your script, one of the icons is named incorrectly because of changing `cat` to some other theme name. `folder-cat-mocha-red-applications.svg` -> `folder-gruv-mat-hard-dark-aqua-appligruv-mations.svg`

I will be updating this script when I'm done with a gtk theme that i am working on. Thanks for pointing it out 👍🏼

**Comment by Vibhav201** [comment]
I've already fixed and modified the script, I'll be done with the GitHub repo by tomorrow. :)

**Comment by Vibhav201** [comment]
> Since you asked I was actually planning to update this one to remove the "light" variant because it looks super dimmed when you have compositor effects that dims the window when its not focused. So my opinion is always stick to lighter colors, only use a dark variant of it if there are words on top of it (bg and fg).

I don't think you should remove the "light" variant because it has its own look. But, I think you should change the colour of the symbol of the icon to a darker colour and the file(small white part) colour to a dimmer grey. 

> The right one looks better but dim the white a bit more if you want to use a monochrome range(?) since there are no other colors present (red, blue, etc).

Sorry, but I removed those icon images because I am making multiple variants and I'll show them to you when all of them are complete.

**Comment by Vibhav201** [comment]
Hey there, here is the repo for the script: https://github.com/Vibhav201/Custom-Papirus-Folder-Icons
Here is the repo for Dracula Folder-Icons: https://github.com/Vibhav201/Dracula-Papirus
Some changes are needed in the instructions but thanks for the help.

**Comment by xelser** [comment]
Well done, good job with it 👏🏼
